// Service pricing seed data for partner pricing system
// These are different from ServicePage (marketing pages)

export const SERVICE_PRICING_SEED_DATA = [
  {
    serviceType: 'custom-web-development',
    serviceName: 'Custom Web Development',
    category: 'Development',
    priceRo: 5000,
    priceIt: 6000,
    priceEn: 6000,
    description: 'Sviluppo applicazione web custom completa con design, backend, frontend e deploy',
    isActive: true,
    isRecurring: false,
  },
  {
    serviceType: 'mvp-sprint-4-weeks',
    serviceName: 'MVP Sprint (4 settimane)',
    category: 'Development',
    priceRo: 4000,
    priceIt: 5000,
    priceEn: 5000,
    description: 'Prototipo funzionale MVP in 4 settimane, feature core + auth + deploy',
    isActive: true,
    isRecurring: false,
  },
  {
    serviceType: 'process-automation',
    serviceName: 'Process Automation',
    category: 'Automation',
    priceRo: 2500,
    priceIt: 3000,
    priceEn: 3000,
    description: 'Automazione workflow e task ripetitivi con integrazioni tra sistemi',
    isActive: true,
    isRecurring: false,
  },
  {
    serviceType: 'system-integration',
    serviceName: 'System Integration',
    category: 'Integration',
    priceRo: 3500,
    priceIt: 4000,
    priceEn: 4000,
    description: 'Integrazione tra sistemi esistenti (CRM, ERP, e-commerce) con API custom',
    isActive: true,
    isRecurring: false,
  },
  {
    serviceType: 'ai-chatbot',
    serviceName: 'AI Chatbot Custom',
    category: 'AI',
    priceRo: 3000,
    priceIt: 3500,
    priceEn: 3500,
    description: 'Chatbot AI personalizzato con training su dati aziendali e integrazioni CRM',
    isActive: true,
    isRecurring: false,
  },
  {
    serviceType: 'restaurant-automation',
    serviceName: 'Restaurant Automation System',
    category: 'Vertical SaaS',
    priceRo: 4000,
    priceIt: 4500,
    priceEn: 4500,
    description: 'Sistema completo gestione ristorante: prenotazioni, ordini, inventario, analytics',
    isActive: true,
    isRecurring: false,
  },
  {
    serviceType: 'marketplace-development',
    serviceName: 'Marketplace Development',
    category: 'E-commerce',
    priceRo: 8000,
    priceIt: 9000,
    priceEn: 9000,
    description: 'Sviluppo marketplace completo con multi-vendor, pagamenti, dashboard seller',
    isActive: true,
    isRecurring: false,
  },
  {
    serviceType: 'logo-design',
    serviceName: 'Logo Design',
    category: 'Design',
    priceRo: 300,
    priceIt: 400,
    priceEn: 400,
    description: 'Logo design professionale con 3 concept, revisioni illimitate',
    isActive: true,
    isRecurring: false,
  },
  {
    serviceType: 'logo-design-brand',
    serviceName: 'Logo Design + Brand Identity',
    category: 'Design',
    priceRo: 800,
    priceIt: 1000,
    priceEn: 1000,
    description: 'Logo + brand identity completa: colors, fonts, guidelines, assets',
    isActive: true,
    isRecurring: false,
  },
  {
    serviceType: 'landing-page',
    serviceName: 'Landing Page',
    category: 'Marketing',
    priceRo: 600,
    priceIt: 800,
    priceEn: 800,
    description: 'Landing page ottimizzata per conversioni con design custom e copywriting',
    isActive: true,
    isRecurring: false,
  },
  {
    serviceType: 'seo-audit',
    serviceName: 'SEO Audit',
    category: 'Marketing',
    priceRo: 400,
    priceIt: 500,
    priceEn: 500,
    description: 'Audit SEO completo: technical, on-page, content con action plan',
    isActive: true,
    isRecurring: false,
  },
  {
    serviceType: 'seo-6-months',
    serviceName: 'SEO 6 Mesi',
    category: 'Marketing',
    priceRo: 1200,
    priceIt: 1500,
    priceEn: 1500,
    description: 'Ottimizzazione SEO continuativa per 6 mesi con report mensili',
    isActive: true,
    isRecurring: true,
  },
  {
    serviceType: 'web-design-complete',
    serviceName: 'Web Design Completo',
    category: 'Design',
    priceRo: 2000,
    priceIt: 2500,
    priceEn: 2500,
    description: 'Design completo sito web: wireframes, mockups, prototype Figma, design system',
    isActive: true,
    isRecurring: false,
  },
  {
    serviceType: 'maintenance-monthly',
    serviceName: 'Manutenzione Mensile',
    category: 'Support',
    priceRo: 200,
    priceIt: 250,
    priceEn: 250,
    description: 'Manutenzione mensile: updates, bug fixes, monitoring, backup',
    isActive: true,
    isRecurring: true,
  },
];
